apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/maxScale: '3'
    run.googleapis.com/urls: '["https://family-travel-v2-preview-805885329896.us-central1.run.app","https://family-travel-v2-preview-jbcpdo3upq-uc.a.run.app"]'
  labels:
    cloud.googleapis.com/location: us-central1
  name: family-travel-v2-preview
  namespace: '805885329896'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '3'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 550.0.0
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: vprilbsnhr
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: GEMINI_API_KEY
          value: AIzaSyAwsgku1C8yARk8H_Pe_CK8pZcXjBEj5mc
        - name: NEXT_PUBLIC_APP_MODE
          value: v2-lab
        image: us-central1-docker.pkg.dev/travelapp05/travel-app-repo/family-app:latest
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        volumeMounts:
        - name: travel-data
          mountPath: /app/src/data
          subPath: data
        - name: travel-data
          mountPath: /app/public/images
          subPath: public/images
        - name: travel-data
          mountPath: /app/public/documents
          subPath: public/documents
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      serviceAccountName: 805885329896-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
      volumes:
      - name: travel-data
        csi:
          driver: gcsfuse.run.googleapis.com
          volumeAttributes:
            bucketName: travelapp05-travel-data
  traffic:
  - latestRevision: true
    percent: 100
